---
- name: Install gcsfuse and mount GCS bucket
  hosts: all
  become: true
  vars:
    bucket_name: "your-gcs-bucket-name"
    mount_point: "/mnt/gcs-bucket"

  tasks:

    - name: Display detected OS family
      debug:
        msg: "Detected OS family: {{ ansible_os_family }}"

    - name: Install required packages (Debian/Ubuntu)
      apt:
        name:
          - curl
          - gnupg
          - lsb-release
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install required packages (RHEL/CentOS/Fedora)
      yum:
        name:
          - curl
          - gnupg
        state: present
      when: ansible_os_family == "RedHat"

    - name: Add gcsfuse apt repository (Debian/Ubuntu)
      apt_repository:
        repo: "deb https://packages.cloud.google.com/apt gcsfuse-{{ ansible_lsb.codename }} main"
        state: present
        filename: gcsfuse
      when: ansible_os_family == "Debian"

    - name: Add Google Cloud apt key (Debian/Ubuntu)
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
      when: ansible_os_family == "Debian"

    - name: Add gcsfuse yum repository (RHEL/CentOS/Fedora)
      yum_repository:
        name: gcsfuse
        description: "gcsfuse (Google Cloud Storage FUSE adapter)"
        baseurl: "https://packages.cloud.google.com/yum/repos/gcsfuse-el$releasever-$basearch"
        gpgcheck: yes
        repo_gpgcheck: yes
        gpgkey:
          - https://packages.cloud.google.com/yum/doc/yum-key.gpg
          - https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
      when: ansible_os_family == "RedHat"

    - name: Install gcsfuse (Debian/Ubuntu)
      apt:
        name: gcsfuse
        state: present
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install gcsfuse (RHEL/CentOS/Fedora)
      yum:
        name: gcsfuse
        state: present
      when: ansible_os_family == "RedHat"

    - name: Enable user_allow_other in fuse.conf
      lineinfile:
        path: /etc/fuse.conf
        regexp: '^#?user_allow_other'
        line: 'user_allow_other'

    - name: Create mount directory
      file:
        path: "{{ mount_point }}"
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Add GCS bucket mount to /etc/fstab
      lineinfile:
        path: /etc/fstab
        line: "{{ bucket_name }} {{ mount_point }} gcsfuse rw,implicit_dirs,uid=0,gid=0,file_mode=777,dir_mode=777,allow_other,_netdev 0 0"
        state: present
        create: yes

    - name: Mount GCS bucket
      mount:
        path: "{{ mount_point }}"
        src: "{{ bucket_name }}"
        fstype: gcsfuse
        opts: rw,implicit_dirs,uid=0,gid=0,file_mode=777,dir_mode=777,allow_other,_netdev
        state: mounted

    - name: Verify mount
      command: mount
      register: mount_output

    - name: Show gcsfuse mount
      debug:
        msg: "{{ mount_output.stdout_lines | select('search', 'gcsfuse') | list }}"
